[package]
name = "metric-query-library"
version = "0.1.0"
edition = "2021"
[lib]
name = "metric_query_library"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.40"
serde = "1.0.219"
pyo3 = { version = "0.24.0", features = ["extension-module"] }
