version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: registry.quantum-forge.net/metrics-api:latest
    container_name: metrics-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./api/test_data.json:/app/test_data.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - metrics-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: registry.quantum-forge.net/metrics-ui:latest
    container_name: metrics-ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - metrics-network

networks:
  metrics-network:
    driver: bridge