apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-test-data
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.api.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  test_data.json: |-
    {
      "basicMetrics": [
        {"value": 990, "timestamp": 1739459679777},
        {"value": 764, "timestamp": 1741694960322},
        {"value": 223, "timestamp": 1741029716851},
        {"value": 218, "timestamp": 1740355862626},
        {"value": 939, "timestamp": 1739929718285},
        {"value": 390, "timestamp": 1740483177432},
        {"value": 452, "timestamp": 1740792163024},
        {"value": 675, "timestamp": 1739698538577},
        {"value": -46, "timestamp": 1741744465053},
        {"value": 238, "timestamp": 1741203736567},
        {"value": 414, "timestamp": 1741434943106},
        {"value": -35, "timestamp": 1740146168274},
        {"value": 124, "timestamp": 1739364777582},
        {"value": 596, "timestamp": 1740977529322},
        {"value": 405, "timestamp": 1739762121974},
        {"value": 721, "timestamp": 1740517274837},
        {"value": 446, "timestamp": 1740062240135},
        {"value": 35, "timestamp": 1740312352631},
        {"value": 407, "timestamp": 1739682123376},
        {"value": -94, "timestamp": 1741111142780},
        {"value": 604, "timestamp": 1740704218983},
        {"value": 61, "timestamp": 1741595593787},
        {"value": 492, "timestamp": 1740141229927},
        {"value": 185, "timestamp": 1740121097143},
        {"value": 678, "timestamp": 1739596212137},
        {"value": 511, "timestamp": 1739619445301},
        {"value": -39, "timestamp": 1739298919884},
        {"value": 797, "timestamp": 1740766243146},
        {"value": 438, "timestamp": 1741569872084},
        {"value": 717, "timestamp": 1741665069129},
        {"value": 351, "timestamp": 1741686145355},
        {"value": 596, "timestamp": 1740308419745},
        {"value": 250, "timestamp": 1739469085744},
        {"value": 387, "timestamp": 1741370698025},
        {"value": -12, "timestamp": 1740298522751},
        {"value": 14, "timestamp": 1740555198040},
        {"value": 401, "timestamp": 1741456527584},
        {"value": 349, "timestamp": 1741550895250},
        {"value": 563, "timestamp": 1739164870570},
        {"value": 777, "timestamp": 1741669592018},
        {"value": 665, "timestamp": 1739818853974},
        {"value": -61, "timestamp": 1741260959838},
        {"value": 501, "timestamp": 1739641527234},
        {"value": 544, "timestamp": 1740068578693},
        {"value": 393, "timestamp": 1739411201011},
        {"value": 839, "timestamp": 1740861640361},
        {"value": 376, "timestamp": 1739505118218},
        {"value": 98, "timestamp": 1740794189654},
        {"value": 828, "timestamp": 1740356301842},
        {"value": 349, "timestamp": 1740717177200}
      ],
      "extendedMetrics": [
        {"label": "CPU_USAGE", "value": 223, "timestamp": 1740386425836},
        {"label": "MEMORY_USAGE", "value": 43, "timestamp": 1741014822525},
        {"label": "DB_CONNECTIONS", "value": 485, "timestamp": 1739495202769},
        {"label": "API_LATENCY", "value": 104, "timestamp": 1741130735617},
        {"label": "CPU_USAGE", "value": -19, "timestamp": 1739507909426},
        {"label": "CPU_USAGE", "value": 962, "timestamp": 1741183199941},
        {"label": "MEMORY_USAGE", "value": -58, "timestamp": 1741680488089},
        {"label": "NETWORK_THROUGHPUT", "value": 440, "timestamp": 1740036858085},
        {"label": "CPU_USAGE", "value": -45, "timestamp": 1741456457846},
        {"label": "DB_CONNECTIONS", "value": 655, "timestamp": 1740262972601},
        {"label": "DB_CONNECTIONS", "value": 406, "timestamp": 1739295687123},
        {"label": "DB_CONNECTIONS", "value": 384, "timestamp": 1739826215831},
        {"label": "DB_CONNECTIONS", "value": 718, "timestamp": 1741285748079},
        {"label": "MEMORY_USAGE", "value": -27, "timestamp": 1739802597589},
        {"label": "API_LATENCY", "value": -89, "timestamp": 1739796228382},
        {"label": "API_LATENCY", "value": 903, "timestamp": 1740966552855},
        {"label": "API_LATENCY", "value": 805, "timestamp": 1741303425854},
        {"label": "CPU_USAGE", "value": 458, "timestamp": 1740104823065},
        {"label": "NETWORK_THROUGHPUT", "value": 732, "timestamp": 1740681452452},
        {"label": "CPU_USAGE", "value": 549, "timestamp": 1741443608359},
        {"label": "CPU_USAGE", "value": 298, "timestamp": 1741631301988},
        {"label": "MEMORY_USAGE", "value": -100, "timestamp": 1741512186684},
        {"label": "MEMORY_USAGE", "value": 365, "timestamp": 1740434783168},
        {"label": "NETWORK_THROUGHPUT", "value": -98, "timestamp": 1741372588370},
        {"label": "API_LATENCY", "value": 907, "timestamp": 1741034526044},
        {"label": "API_LATENCY", "value": 557, "timestamp": 1740593962968},
        {"label": "CPU_USAGE", "value": 80, "timestamp": 1741743614299},
        {"label": "DB_CONNECTIONS", "value": 210, "timestamp": 1739392663515},
        {"label": "CPU_USAGE", "value": -41, "timestamp": 1741248230809},
        {"label": "MEMORY_USAGE", "value": 42, "timestamp": 1740359005316},
        {"label": "MEMORY_USAGE", "value": -48, "timestamp": 1739626694895},
        {"label": "MEMORY_USAGE", "value": 778, "timestamp": 1740439536261},
        {"label": "CPU_USAGE", "value": 469, "timestamp": 1740790748990},
        {"label": "API_LATENCY", "value": 793, "timestamp": 1739353052996},
        {"label": "DB_CONNECTIONS", "value": 325, "timestamp": 1739588619232},
        {"label": "API_LATENCY", "value": 744, "timestamp": 1739922848426},
        {"label": "NETWORK_THROUGHPUT", "value": 147, "timestamp": 1741737562538},
        {"label": "CPU_USAGE", "value": 330, "timestamp": 1740394699334},
        {"label": "CPU_USAGE", "value": 832, "timestamp": 1739475209162},
        {"label": "CPU_USAGE", "value": 580, "timestamp": 1739932762477},
        {"label": "API_LATENCY", "value": -45, "timestamp": 1741700974418},
        {"label": "MEMORY_USAGE", "value": 6, "timestamp": 1739245664864},
        {"label": "NETWORK_THROUGHPUT", "value": 255, "timestamp": 1740192627395},
        {"label": "API_LATENCY", "value": 817, "timestamp": 1741270475871},
        {"label": "DB_CONNECTIONS", "value": 502, "timestamp": 1739562075400},
        {"label": "NETWORK_THROUGHPUT", "value": 142, "timestamp": 1740228386332},
        {"label": "NETWORK_THROUGHPUT", "value": 51, "timestamp": 1741274449707},
        {"label": "MEMORY_USAGE", "value": 724, "timestamp": 1740563359198},
        {"label": "DB_CONNECTIONS", "value": 676, "timestamp": 1740968217560},
        {"label": "MEMORY_USAGE", "value": -93, "timestamp": 1739351765511}
      ]
    }