global:
  environment: production

api:
  replicaCount: 2
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

ui:
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: metrics-demandbase.rileyseaburg.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: metrics-ui-service
          servicePort: 80
    - host: api-metrics-demandbase.rileyseaburg.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: metrics-api-service
          servicePort: 80
  tls:
    - secretName: metrics-tls-secret
      hosts:
        - metrics-demandbase.rileyseaburg.com
        - api-metrics-demandbase.rileyseaburg.com